const endpoints = [
  ['Core', 'Pokédex completa', 'v1/pokedex.json', 'Especies, formas, tipos, movimientos y combate.'],
  ['Core', 'Pokémon individual', 'v1/pokemon/25.json', 'Documento ligero por número de Pokédex.'],
  ['Core', 'Formas', 'v1/forms.json', 'Formas regionales, especiales y disfraces.'],
  ['Core', 'Tipos', 'v1/types.json', 'Catálogo de los 18 tipos.'],
  ['Core', 'Efectividad', 'v1/type-effectiveness.json', 'Matriz de multiplicadores ofensivos y defensivos.'],
  ['Combate', 'Movimientos', 'v1/moves.json', 'Datos PvE, PvP, energía, turnos y buffs.'],
  ['Combate', 'Estadísticas', 'v1/combat.json', 'CP máximo, bulk y producto estadístico.'],
  ['Combate', 'Rankings', 'v1/rankings.json', 'Top por ataque, defensa, stamina, bulk y CP.'],
  ['Combate', 'Rankings PvP', 'v1/pvp-rankings.json', 'Liga Super, Ultra y Master por producto estadístico.'],
  ['Combate', 'Movesets PvP', 'v1/pvp-movesets.json', 'Movimientos recomendados, alternativas y métricas explicables.'],
  ['Evolución', 'Evoluciones', 'v1/evolutions.json', 'Relaciones y costes de evolución.'],
  ['Evolución', 'Familias', 'v1/families.json', 'Familias completas y sus rutas.'],
  ['Evolución', 'Megaevoluciones', 'v1/temporary-evolutions.json', 'Estadísticas y costes de Mega Energy.'],
  ['Evolución', 'Gigamax', 'v1/gigantamax.json', 'Pokémon y movimientos Gigamax.'],
  ['Mundo', 'Objetos', 'v1/items.json', 'Objetos, categorías y nivel requerido.'],
  ['Mundo', 'Clima', 'v1/weather.json', 'Climas y tipos potenciados.'],
  ['Mundo', 'Incursiones', 'v1/raids.json', 'Catálogo de niveles de incursión.'],
  ['En vivo', 'Eventos activos', 'v1/live/events/active.json', 'Eventos vigentes calculados durante cada despliegue.'],
  ['En vivo', 'Próximos eventos', 'v1/live/events/upcoming.json', 'Agenda de eventos futuros.'],
  ['En vivo', 'Incursiones activas', 'v1/live/active-raids.json', 'Jefes de incursión disponibles actualmente.'],
  ['En vivo', 'Jefes de incursión', 'v1/live/raid-bosses.json', 'Tier, shiny, tipos, CP y clima desde DataDuck.'],
  ['En vivo', 'Huevos', 'v1/live/eggs.json', 'Pools de huevos, rareza, regionales y shiny.'],
  ['En vivo', 'Investigaciones', 'v1/live/research.json', 'Tareas de campo y recompensas actuales.'],
  ['En vivo', 'Team GO Rocket', 'v1/live/rocket.json', 'Líderes, equipos y encuentros disponibles.'],
  ['En vivo', 'Calendario', 'v1/live/calendar.json', 'Eventos e incursiones en una sola cronología.'],
  ['Mundo', 'Invasiones Rocket', 'v1/invasions.json', 'Equipos y encuentros del Team GO Rocket.'],
  ['Mundo', 'Disfraces', 'v1/costumes.json', 'Disfraces y restricciones de evolución.'],
  ['Mundo', 'Location Cards', 'v1/location-cards.json', 'Tarjetas de ubicación y recursos asociados.'],
  ['Misiones', 'Tipos de misión', 'v1/quest-types.json', 'Catálogo de acciones de investigación.'],
  ['Misiones', 'Condiciones', 'v1/quest-conditions.json', 'Condiciones aplicables a misiones.'],
  ['Misiones', 'Recompensas', 'v1/quest-reward-types.json', 'Tipos de recompensa disponibles.'],
  ['Sistema', 'Equipos', 'v1/teams.json', 'Equipos definidos por el juego.'],
  ['Sistema', 'Tipos de ruta', 'v1/route-types.json', 'Catálogo de rutas.'],
  ['Sistema', 'Idiomas', 'v1/translations.json', 'Manifiesto de traducciones disponibles.'],
  ['Sistema', 'Metadatos', 'v1/meta.json', 'Versión, fuente, fecha y cantidades.'],
  ['Recursos', 'Explorador', 'v1/explorer.json', 'Índice compacto para construir interfaces visuales.'],
  ['Recursos', 'Sprites', 'v1/sprites.json', 'Sprites de Pokémon GO con URLs de respaldo.'],
  ['Recursos', 'Buscador global', 'v1/search.json', 'Índice compacto de especies, formas y disponibilidad.'],
  ['En vivo', 'Disponibilidad', 'v1/availability.json', 'Disponibilidad unificada por Pokémon y fuente.'],
  ['En vivo', 'Índice de incursiones', 'v1/indexes/by-availability/raids.json', 'Pokémon actualmente detectados en incursiones.'],
  ['Historial', 'Últimos cambios', 'v1/changes/latest.json', 'Resumen de altas, bajas y modificaciones por dataset.'],
  ['Historial', 'Cambios en incursiones', 'v1/changes/raids.json', 'Rotaciones detectadas entre dos despliegues.'],
  ['Historial', 'Índice histórico', 'v1/history/index.json', 'Manifiesto de snapshots de cambios disponibles.'],
  ['Incursiones', 'Guías activas', 'v1/raid-guides/index.json', 'Debilidades, CP, clima y counters para los jefes actuales.'],
  ['Incursiones', 'Guía individual', 'v1/raid-guides/382.json', 'Top de counters y movimientos contra un jefe concreto.'],
] as const

function endpointCards() {
  return endpoints.map(([category, name, path, description]) => `
    <article class="endpoint" data-search="${category} ${name} ${path} ${description}">
      <div class="endpoint-top"><span class="tag">${category}</span><span class="method">GET</span></div>
      <h3>${name}</h3><p>${description}</p>
      <div class="url"><a href="${path}" target="_blank" rel="noreferrer"><code>/${path}</code></a><button class="copy" data-copy="${path}" aria-label="Copiar /${path}">Copiar</button></div>
    </article>`).join('')
}

export function docsHtml() {
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="API JSON estática, abierta y versionada de datos de Pokémon GO.">
<title>PoGo Data API — Documentación</title>
<style>
:root{--bg:#07111f;--panel:#0d1a2c;--panel2:#101f34;--line:#203451;--text:#eef6ff;--muted:#91a5bf;--blue:#62a8ff;--cyan:#55e6c1;--violet:#9b87ff;--shadow:0 24px 70px #0006;color-scheme:dark}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 78% -10%,#183b68 0,transparent 34%),radial-gradient(circle at 12% 15%,#173349 0,transparent 25%),var(--bg);color:var(--text);font:15px/1.6 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
a{color:inherit;text-decoration:none}button,input{font:inherit}.wrap{width:min(1160px,calc(100% - 36px));margin:auto}
header{height:70px;display:flex;align-items:center;border-bottom:1px solid #ffffff12;position:sticky;top:0;z-index:5;background:#07111fd9;backdrop-filter:blur(16px)}nav{display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{font-weight:850;letter-spacing:-.03em;font-size:18px}.brand i{display:inline-block;width:10px;height:10px;border-radius:50%;background:var(--cyan);box-shadow:0 0 20px var(--cyan);margin-right:10px}.navlinks{display:flex;gap:24px;color:var(--muted);font-size:14px}.navlinks a:hover{color:var(--text)}
.hero{padding:92px 0 70px;position:relative}.eyebrow{display:inline-flex;align-items:center;gap:9px;border:1px solid #55e6c150;background:#55e6c10d;color:#8af3d8;border-radius:999px;padding:6px 12px;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.09em}.pulse{width:7px;height:7px;border-radius:50%;background:var(--cyan);box-shadow:0 0 0 5px #55e6c118}
h1{font-size:clamp(46px,8vw,82px);line-height:.98;letter-spacing:-.065em;margin:25px 0 23px;max-width:900px}.gradient{background:linear-gradient(100deg,#fff 10%,var(--blue) 55%,var(--cyan));-webkit-background-clip:text;color:transparent}.lead{font-size:19px;color:var(--muted);max-width:690px;margin:0 0 33px}.actions{display:flex;gap:12px;flex-wrap:wrap}.btn{border:1px solid var(--line);padding:11px 17px;border-radius:10px;font-weight:750;background:#ffffff08;cursor:pointer;color:var(--text)}.btn.primary{background:linear-gradient(120deg,#3a82ee,#6557d8);border-color:transparent;box-shadow:0 10px 28px #3a82ee35}.btn:hover{transform:translateY(-1px);border-color:#52739e}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:58px}.stat{background:linear-gradient(145deg,#ffffff0b,#ffffff04);border:1px solid #ffffff14;border-radius:14px;padding:19px}.stat strong{font-size:27px;display:block;letter-spacing:-.04em}.stat span{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em}
section{padding:58px 0}.section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:25px}.section-head h2{font-size:32px;letter-spacing:-.04em;margin:0}.section-head p{color:var(--muted);margin:5px 0 0}.search{width:min(330px,100%);padding:12px 14px;border-radius:10px;border:1px solid var(--line);background:#081423;color:var(--text);outline:none}.search:focus{border-color:var(--blue);box-shadow:0 0 0 3px #62a8ff18}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.endpoint{background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:14px;padding:18px;min-width:0;transition:.2s ease}.endpoint:hover{border-color:#3c5d86;transform:translateY(-2px);box-shadow:var(--shadow)}.endpoint-top{display:flex;justify-content:space-between}.tag{font-size:11px;color:#b7c9df;background:#ffffff0a;padding:3px 8px;border-radius:999px}.method{font:bold 11px ui-monospace,SFMono-Regular,monospace;color:var(--cyan)}.endpoint h3{margin:15px 0 4px;font-size:17px}.endpoint p{color:var(--muted);margin:0 0 16px;min-height:48px}.url{display:flex;align-items:center;gap:8px;background:#06101d;border:1px solid #1b304c;border-radius:8px;padding:7px 7px 7px 10px}.url code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#a9c9f4;font-size:12px}.copy{margin-left:auto;border:0;background:#1a2d47;color:#cce1fb;border-radius:6px;padding:5px 8px;cursor:pointer;font-size:11px}.copy:hover{background:#29486f}.copy.done{background:#154b41;color:#8af3d8}
.quick{display:grid;grid-template-columns:1fr 1fr;gap:15px}.codebox{background:#050d18;border:1px solid var(--line);border-radius:14px;overflow:hidden}.codehead{display:flex;justify-content:space-between;padding:10px 14px;border-bottom:1px solid var(--line);color:var(--muted);font-size:12px}.codebox pre{margin:0;padding:20px;overflow:auto;color:#b9d4f7;font:13px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace}.architecture{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.step{border-left:2px solid var(--violet);background:#ffffff06;padding:17px;border-radius:0 12px 12px 0}.step b{display:block;margin-bottom:5px}.step span{color:var(--muted)}
.dexgrid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.poke{min-width:0;background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:14px;padding:13px;text-align:center;transition:.2s}.poke:hover{transform:translateY(-3px);border-color:#426c9d}.poke img{width:96px;height:96px;object-fit:contain}.poke small{display:block;color:var(--muted)}.poke b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.types{display:flex;justify-content:center;gap:4px;margin-top:7px;min-height:20px}.type{font-size:9px;text-transform:uppercase;background:#ffffff0d;border-radius:99px;padding:2px 6px}.dexmore{display:block;margin:20px auto 0}.sprite-note{text-align:center;color:var(--muted);font-size:12px;margin-top:14px}.league-tabs{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}.league-tabs button.active{background:#315f9c;border-color:#62a8ff}.ranking{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.rankrow{display:grid;grid-template-columns:40px 52px 1fr auto;align-items:center;gap:10px;background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:12px;padding:9px 13px}.rankrow img{width:48px;height:48px;object-fit:contain}.ranknum{font-size:18px;font-weight:850;color:var(--cyan)}.rankrow small{display:block;color:var(--muted)}.score{text-align:right}.score b{display:block;color:#9fc8ff}.livegrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.livecard{background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:14px;padding:17px}.livecard .status{display:inline-block;color:var(--cyan);background:#55e6c112;border:1px solid #55e6c134;border-radius:99px;padding:2px 8px;font-size:10px;text-transform:uppercase}.livecard h3{margin:12px 0 5px}.livecard p,.livecard time{display:block;color:var(--muted);margin:0;font-size:13px}.emptylive{grid-column:1/-1;text-align:center;border:1px dashed var(--line);border-radius:14px;padding:35px;color:var(--muted)}.changegrid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:14px}.changeitem{background:#ffffff07;border:1px solid var(--line);border-radius:10px;padding:11px}.changeitem b{display:block;text-transform:capitalize}.changeitem span{color:var(--muted);font-size:12px}.baseline{grid-column:1/-1;color:var(--muted);font-size:12px}.guidegrid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.guide{background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:14px;padding:13px;text-align:center}.guide:hover{border-color:var(--blue);transform:translateY(-2px)}.guide img{width:82px;height:82px;object-fit:contain}.guide b,.guide small{display:block}.guide small{color:var(--muted)}
footer{border-top:1px solid #ffffff12;padding:34px 0 50px;color:var(--muted)}.footerline{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.hidden{display:none!important}
@media(max-width:1000px){.dexgrid{grid-template-columns:repeat(4,1fr)}}
@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}.quick{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.architecture{grid-template-columns:1fr}.navlinks{display:none}.dexgrid{grid-template-columns:repeat(3,1fr)}.ranking{grid-template-columns:1fr}.livegrid{grid-template-columns:1fr 1fr}.changegrid{grid-template-columns:repeat(2,1fr)}.guidegrid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:560px){.grid{grid-template-columns:1fr}.section-head{align-items:stretch;flex-direction:column}.search{width:100%}.hero{padding-top:62px}h1{font-size:47px}.stats{grid-template-columns:1fr 1fr}.stat strong{font-size:22px}.dexgrid{grid-template-columns:repeat(2,1fr)}.rankrow{grid-template-columns:30px 44px 1fr}.rankrow img{width:42px;height:42px}.score{display:none}.livegrid{grid-template-columns:1fr}.guidegrid{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<header><nav class="wrap"><a class="brand" href="#top"><i></i>PoGo Data API</a><div class="navlinks"><a href="#explorer">Explorador</a><a href="#pvp">PvP</a><a href="#live">En vivo</a><a href="#endpoints">Endpoints</a><a href="#quickstart">Inicio rápido</a><a href="v1/meta.json">Estado</a></div></nav></header>
<main id="top"><div class="hero wrap"><span class="eyebrow"><span class="pulse"></span>API operativa · v1</span><h1>Datos de Pokémon GO,<br><span class="gradient">listos para construir.</span></h1><p class="lead">Una API JSON abierta, rápida y versionada. Sin claves, sin servidor y con actualizaciones automáticas desde GitHub Actions.</p><div class="actions"><a class="btn primary" href="#endpoints">Explorar endpoints</a><button class="btn" data-copy="">Copiar URL base</button></div>
<div class="stats"><div class="stat"><strong id="pokemonCount">—</strong><span>Pokémon</span></div><div class="stat"><strong id="formsCount">—</strong><span>Formas</span></div><div class="stat"><strong id="movesCount">—</strong><span>Movimientos</span></div><div class="stat"><strong id="updatedAt">—</strong><span>Última actualización</span></div></div></div>
<section id="explorer"><div class="wrap"><div class="section-head"><div><h2>Explorador Pokémon</h2><p>Busca especies y abre su documento individual.</p></div><input id="pokemonSearch" class="search" type="search" placeholder="Buscar por nombre o número…" aria-label="Buscar Pokémon"></div><div id="dexGrid" class="dexgrid"><p class="muted">Cargando Pokédex…</p></div><button id="dexMore" class="btn dexmore hidden">Mostrar más</button><p class="sprite-note">Imágenes remotas de PokeMiners/pogo_assets, con respaldo de PokéAPI. Uso educativo; Pokémon y sus recursos pertenecen a The Pokémon Company y Niantic.</p></div></section>
<section id="pvp"><div class="wrap"><div class="section-head"><div><h2>Rankings PvP</h2><p>Mejores productos estadísticos posibles para cada límite de CP.</p></div><a class="btn" href="v1/pvp-rankings.json">Abrir JSON</a></div><div class="league-tabs"><button class="btn active" data-league="great">Liga Super</button><button class="btn" data-league="ultra">Liga Ultra</button><button class="btn" data-league="master">Liga Master</button></div><div id="pvpRanking" class="ranking"><p class="muted">Calculando rankings…</p></div><p class="sprite-note">Clasificación analítica por estadísticas e IV óptimos; no representa simulaciones de enfrentamientos ni el metajuego.</p></div></section>
<section id="live"><div class="wrap"><div class="section-head"><div><h2>Eventos e incursiones</h2><p>Actividad vigente y próxima administrada desde tu repositorio.</p></div><a class="btn" href="v1/live/calendar.json">Abrir calendario</a></div><div id="liveGrid" class="livegrid"><p class="emptylive">Cargando calendario…</p></div><div id="changeSummary" class="changegrid"><p class="baseline">Comprobando cambios recientes…</p></div></div></section>
<section id="raid-guides"><div class="wrap"><div class="section-head"><div><h2>Guías de incursión</h2><p>Counters calculados para los jefes de la rotación actual.</p></div><a class="btn" href="v1/raid-guides/index.json">Abrir índice</a></div><div id="guideGrid" class="guidegrid"><p class="emptylive">Cargando guías…</p></div></div></section>
<section id="endpoints"><div class="wrap"><div class="section-head"><div><h2>Catálogo de endpoints</h2><p>Todo se sirve como JSON estático con rutas estables bajo <code>/v1</code>.</p></div><input id="search" class="search" type="search" placeholder="Buscar Pokémon, combate, clima…" aria-label="Buscar endpoints"></div><div id="endpointGrid" class="grid">${endpointCards()}</div></div></section>
<section id="quickstart"><div class="wrap"><div class="section-head"><div><h2>Inicio rápido</h2><p>Consume los datos desde cualquier proyecto web o backend.</p></div></div><div class="quick"><div class="codebox"><div class="codehead"><span>JavaScript</span><button class="copy" data-code="jsExample">Copiar</button></div><pre id="jsExample">const response = await fetch(
  'https://gaelvm.github.io/pogo-data-api/v1/pokemon/25.json'
)
const pikachu = await response.json()
console.log(pikachu.forms)</pre></div><div class="codebox"><div class="codehead"><span>curl</span><button class="copy" data-code="curlExample">Copiar</button></div><pre id="curlExample">curl https://gaelvm.github.io/pogo-data-api/v1/meta.json</pre></div></div></div></section>
<section><div class="wrap"><div class="section-head"><div><h2>Diseñada para permanecer disponible</h2><p>El cliente nunca depende directamente de las fuentes de generación.</p></div></div><div class="architecture"><div class="step"><b>1. Generación</b><span>GitHub Actions obtiene y valida un snapshot completo.</span></div><div class="step"><b>2. Normalización</b><span>Los datos se transforman a un esquema propio y versionado.</span></div><div class="step"><b>3. Distribución</b><span>GitHub Pages entrega JSON globalmente, sin autenticación.</span></div></div></div></section></main>
<footer><div class="wrap footerline"><span>PoGo Data API · Proyecto comunitario no afiliado</span><span id="datasetVersion">Dataset —</span></div></footer>
<script>
const base=new URL('./',location.href);const absolute=p=>new URL(p,base).href;
async function copy(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copiado ✓';button.classList.add('done');setTimeout(()=>{button.textContent=old;button.classList.remove('done')},1500)}catch{prompt('Copia esta URL:',text)}}
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copy(absolute(b.dataset.copy),b)));
document.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>copy(document.getElementById(b.dataset.code).textContent,b)));
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('.endpoint').forEach(card=>card.classList.toggle('hidden',!card.dataset.search.toLowerCase().includes(q)))});
let dex=[],dexLimit=24;const safe=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function dexMatches(p,q){return !q||p.name.toLowerCase().includes(q)||String(p.id)===q}
function renderDex(){const q=document.getElementById('pokemonSearch').value.toLowerCase().trim();const all=dex.filter(p=>dexMatches(p,q));const visible=all.slice(0,dexLimit);document.getElementById('dexGrid').innerHTML=visible.map(p=>'<a class="poke" href="v1/pokemon/'+p.id+'.json" target="_blank" rel="noreferrer"><img loading="lazy" src="'+safe(p.sprites.default)+'" data-fallback="'+safe(p.sprites.fallbackDefault||'')+'" onerror="if(this.dataset.fallback){this.src=this.dataset.fallback;this.dataset.fallback=null}" alt="'+safe(p.name)+'"><small>#'+String(p.id).padStart(4,'0')+'</small><b>'+safe(p.name)+'</b><div class="types">'+p.types.map(t=>'<span class="type">'+safe(t.name)+'</span>').join('')+'</div></a>').join('')||'<p class="muted">Sin resultados.</p>';document.getElementById('dexMore').classList.toggle('hidden',visible.length>=all.length)}
document.getElementById('pokemonSearch').addEventListener('input',()=>{dexLimit=24;renderDex()});document.getElementById('dexMore').addEventListener('click',()=>{dexLimit+=24;renderDex()});fetch('v1/explorer.json').then(r=>r.json()).then(data=>{dex=data;renderDex()}).catch(()=>{document.getElementById('dexGrid').innerHTML='<p class="muted">No se pudo cargar el explorador.</p>'});
let pvpData,pvpMoves=new Map;function renderLeague(key){const league=pvpData.leagues[key];document.querySelectorAll('[data-league]').forEach(button=>button.classList.toggle('active',button.dataset.league===key));document.getElementById('pvpRanking').innerHTML=league.rankings.slice(0,10).map(p=>{const id=String(p.pokemonId).padStart(3,'0');const image='https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon/pokemon_icon_'+id+'_00.png';const set=pvpMoves.get(p.pokemonId+':'+p.formId);const moves=set?'<small>'+safe(set.fast.name)+' · '+set.charged.map(m=>safe(m.name)).join(' + ')+'</small>':'';return '<a class="rankrow" href="v1/pokemon/'+p.pokemonId+'.json"><span class="ranknum">#'+p.rank+'</span><img loading="lazy" src="'+image+'" alt=""><span><b>'+safe(p.pokemonName)+'</b><small>CP '+p.cp+' · Nv. '+p.level+' · IV '+p.ivs.attack+'/'+p.ivs.defense+'/'+p.ivs.stamina+'</small>'+moves+'</span><span class="score"><b>'+p.score+'</b><small>score</small></span></a>'}).join('')||'<p class="muted">No hay candidatos para esta liga.</p>'}document.querySelectorAll('[data-league]').forEach(button=>button.addEventListener('click',()=>pvpData&&renderLeague(button.dataset.league)));Promise.all([fetch('v1/pvp-rankings.json').then(r=>r.json()),fetch('v1/pvp-movesets.json').then(r=>r.json())]).then(([rankings,moves])=>{pvpData=rankings;pvpMoves=new Map(moves.entries.map(entry=>[entry.pokemonId+':'+entry.formId,entry.recommendation]));renderLeague('great')}).catch(()=>{document.getElementById('pvpRanking').innerHTML='<p class="muted">No se pudieron cargar los rankings.</p>'});
fetch('v1/live/calendar.json').then(r=>r.json()).then(entries=>{const visible=entries.filter(entry=>entry.status!=='past').slice(0,6);document.getElementById('liveGrid').innerHTML=visible.map(entry=>'<article class="livecard"><span class="status">'+(entry.status==='active'?'Activo':'Próximo')+' · '+(entry.kind==='raid'?'Incursión':'Evento')+'</span><h3>'+safe(entry.name)+'</h3><time>'+new Date(entry.startsAt).toLocaleString('es-PE',{dateStyle:'medium',timeStyle:'short'})+' → '+new Date(entry.endsAt).toLocaleString('es-PE',{dateStyle:'medium',timeStyle:'short'})+'</time>'+(entry.description?'<p>'+safe(entry.description)+'</p>':'')+'</article>').join('')||'<p class="emptylive">DataDuck todavía no publicó eventos activos o próximos.</p>'}).catch(()=>{document.getElementById('liveGrid').innerHTML='<p class="emptylive">No se pudo cargar el calendario.</p>'});
fetch('v1/changes/latest.json').then(r=>r.json()).then(data=>{document.getElementById('changeSummary').innerHTML=data.hasPreviousSnapshot?Object.entries(data.summary).map(([name,count])=>'<a class="changeitem" href="v1/changes/'+name+'.json"><b>'+safe(name)+'</b><span>+'+count.added+' · −'+count.removed+' · '+count.updated+' modificados</span></a>').join(''):'<p class="baseline">Línea base creada. Los cambios aparecerán a partir del siguiente despliegue.</p>'}).catch(()=>{document.getElementById('changeSummary').innerHTML=''});
fetch('v1/raid-guides/index.json').then(r=>r.json()).then(guides=>{document.getElementById('guideGrid').innerHTML=guides.map(guide=>{const id=String(guide.pokemonId).padStart(3,'0');return '<a class="guide" href="v1/raid-guides/'+guide.pokemonId+'.json"><img loading="lazy" src="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon/pokemon_icon_'+id+'_00.png" alt=""><b>'+safe(guide.pokemonName)+'</b><small>'+safe(guide.tier)+'</small></a>'}).join('')||'<p class="emptylive">No hay guías disponibles para la rotación actual.</p>'}).catch(()=>{document.getElementById('guideGrid').innerHTML='<p class="emptylive">No se pudieron cargar las guías.</p>'});
fetch('v1/meta.json').then(r=>r.json()).then(m=>{document.getElementById('pokemonCount').textContent=(m.counts.pokemon||0).toLocaleString('es');document.getElementById('formsCount').textContent=(m.counts.forms||0).toLocaleString('es');document.getElementById('movesCount').textContent=(m.counts.moves||0).toLocaleString('es');document.getElementById('updatedAt').textContent=new Date(m.generatedAt).toLocaleDateString('es',{day:'2-digit',month:'short',year:'numeric'});document.getElementById('datasetVersion').textContent='Dataset '+m.datasetVersion}).catch(()=>{});
</script></body></html>`
}
